name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Download wait-for-it.sh
        run: |
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh

      - name: Download Cloud SQL Proxy
        run: |
          wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.16.0/cloud-sql-proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - name: Start Cloud SQL Proxy
        run: |
          ./cloud_sql_proxy --address 0.0.0.0 --port 5432 ${{ secrets.GCP_PROJECT }}:${{ vars.TEST_DB_ZONE }}:${{ vars.TEST_DB_NAME }} &

      - name: Wait for Cloud SQL Proxy to Start
        run: |
          ./wait-for-it.sh 127.0.0.1:5432 -s -t 10 -- echo "Cloud SQL Proxy is running"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: 'Set Up Credentials JSON'
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "bucket_key.json"
          json: ${{ secrets.BUCKET_KEY }}
          dir: "app/"

      - name: Run Unit Test
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: |
          pytest --cov=app --cov-report=term-missing
